version: '3'
services:
  api:
    container_name: api
    command: npm start
    restart: always
    build: .
    ports:
      - "6006:6006"
    networks:
      - bcapp
    volumes:
      - .:/usr/app/    
  whoami-web:
    container_name: whoami-api
    image: containous/whoami
    restart: always
    ports: 
      - "6030:80"
volumes:
  api:
networks:
  bcapp:
    external: true 